import 'dart:typed_data';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import '../models/bill_model.dart';
import '../models/bill_item_model.dart';

class InvoiceService {
  static const String shopName = 'Chaudhary Kirana Store';
  static const String shopAddress = 'Sardar Pur Road, Kabirwala, Punjab, Pakistan';
  static const String shopPhone = 'Phone: +92 3086973210';

  static Future<Uint8List> generateInvoicePdf({
    required Bill bill,
    required List<BillItem> items,
    required String qrData,
  }) async {
    final doc = pw.Document();

    doc.addPage(
      pw.Page(
        pageFormat: PdfPageFormat.roll80,
        margin: const pw.EdgeInsets.symmetric(horizontal: 8, vertical: 12),
        build: (context) {
          return pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              _buildHeader(),
              pw.SizedBox(height: 8),
              pw.Divider(thickness: 1, color: PdfColors.grey700),
              _buildBillMeta(bill),
              pw.SizedBox(height: 8),
              _buildItemsTable(items),
              pw.SizedBox(height: 8),
              pw.Divider(thickness: 1, color: PdfColors.grey700),
              _buildTotals(bill),
              pw.SizedBox(height: 16),
              _buildFooter(),
            ],
          );
        },
      ),
    );

    return doc.save();
  }

  static pw.Widget _buildHeader() {
    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.center,
      children: [
        pw.Text(shopName, style: pw.TextStyle(fontSize: 14, fontWeight: pw.FontWeight.bold)),
        pw.SizedBox(height: 3),
        pw.Text(shopAddress, style: const pw.TextStyle(fontSize: 8), textAlign: pw.TextAlign.center),
        pw.Text(shopPhone, style: const pw.TextStyle(fontSize: 8)),
      ],
    );
  }

  static pw.Widget _buildBillMeta(Bill bill) {
    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        pw.Row(
          mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
          children: [
            pw.Text('Bill #: ${bill.id ?? '-'}', style: pw.TextStyle(fontSize: 9, fontWeight: pw.FontWeight.bold)),
            pw.Text('Date: ${bill.date}', style: const pw.TextStyle(fontSize: 8)),
          ],
        ),
        pw.SizedBox(height: 2),
        pw.Text('Customer: ${bill.customerName}', style: const pw.TextStyle(fontSize: 8)),
      ],
    );
  }

  static pw.Widget _buildItemsTable(List<BillItem> items) {
    final headers = ['Product', 'Qty', 'Price', 'Total'];
    final rows = items.map((item) {
      final String unitLabel = (item.unit != null && item.unit!.trim().isNotEmpty) ? ' (${item.unit})' : '';
      return [
        '${item.productName}$unitLabel',
        item.quantity.toString(),
        item.unitPrice.toStringAsFixed(1),
        item.totalPrice.toStringAsFixed(1),
      ];
    }).toList();

    return pw.TableHelper.fromTextArray(
      headers: headers,
      data: rows,
      headerStyle: pw.TextStyle(fontWeight: pw.FontWeight.bold, fontSize: 8),
      cellStyle: const pw.TextStyle(fontSize: 8),
      cellAlignments: {0: pw.Alignment.centerLeft, 1: pw.Alignment.center, 2: pw.Alignment.centerRight, 3: pw.Alignment.centerRight},
      headerDecoration: const pw.BoxDecoration(color: PdfColors.grey200),
      border: const pw.TableBorder(
        horizontalInside: pw.BorderSide(color: PdfColors.grey300, width: 0.5),
        bottom: pw.BorderSide(color: PdfColors.grey400, width: 0.5),
      ),
    );
  }

  static pw.Widget _buildTotals(Bill bill) {
    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.end,
      children: [
        _totalRow('Subtotal', bill.subtotal),
        if (bill.extraCharges > 0) _totalRow('Extra', bill.extraCharges),
        pw.SizedBox(height: 2),
        pw.Row(
          mainAxisAlignment: pw.MainAxisAlignment.end,
          children: [
            pw.Text('Grand Total: ', style: pw.TextStyle(fontSize: 10, fontWeight: pw.FontWeight.bold)),
            pw.Text(bill.grandTotal.toStringAsFixed(2), style: pw.TextStyle(fontSize: 10, fontWeight: pw.FontWeight.bold)),
          ],
        ),
      ],
    );
  }

  static pw.Widget _totalRow(String label, double value) {
    return pw.Row(
      mainAxisAlignment: pw.MainAxisAlignment.end,
      children: [
        pw.Text('$label: ', style: const pw.TextStyle(fontSize: 8)),
        pw.Text(value.toStringAsFixed(1), style: const pw.TextStyle(fontSize: 8)),
      ],
    );
  }

  static pw.Widget _buildFooter() {
    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.center,
      children: [
        pw.Divider(thickness: 0.5, color: PdfColors.grey600),
        pw.SizedBox(height: 4),
        pw.Text('Thank you for shopping with us!', style: pw.TextStyle(fontSize: 8, fontWeight: pw.FontWeight.bold)),
        pw.SizedBox(height: 3),
        pw.Text('Generated by RetailFlow\nDeveloped by Mr. Arshad +92 3127461403', style: const pw.TextStyle(fontSize: 7, color: PdfColors.grey600), textAlign: pw.TextAlign.center),
      ],
    );
  }
}